# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Username', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Pass', models.CharField(max_length=255)),
                ('CPass', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='ItemObj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ITEM', to='belt3.User'),
        ),
        migrations.AddField(
            model_name='item',
            name='UserObj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='USER', to='belt3.User'),
        ),
    ]
